import { useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Loader from '../components/loader/Loader'
import PreloadImages from '../components/loader/PreloadImages'
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter()

  const onStart = () => router.push('/welcome')

  useEffect(() => {
    setTimeout(() => onStart(), 5000)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>25 Apples</title>
        <link rel="icon" href="/apple_icon.png" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
      </Head>
      <main
        style={{ display: 'flex', justifyContent: 'center', paddingTop: '10rem', height: '20rem' }}
      >
        <PreloadImages />
        <Loader />
      </main>
    </div>
  )
}
