import Head from 'next/head';
import Image from 'next/image';
import { useState, useEffect, useRef } from 'react';
import styles from '../styles/Home.module.css';
import { CSSTransition } from 'react-transition-group';
import slideTransition from '../styles/transitions/titleSlide.module.css'; 
import fadeTransition from '../styles/transitions/titleFade.module.css'; 
import Title from '../components/title/Title';
import Apples from '../components/title/Apples';


export default function Test() {

    const [isShow, setIsShow] = useState(false);
    useEffect(() => setIsShow(true), []);

    // const nodeRef = useRef(null);

    return (
        <div className={styles.container}>
            <Head>
                <title>25 Apples</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className={styles.main} style={{justifyContent: 'flex-end'}}>
                <CSSTransition appear={true} in={isShow===true} classNames={fadeTransition} timeout={1000} unmountOnExit>
                    <Title show={setIsShow} />
                </CSSTransition>
                <CSSTransition appear={true} in={isShow===true} classNames={slideTransition} timeout={1000} unmountOnExit>
                    <Apples />
                </CSSTransition>
            </main>
        </div>
    )
};
