import { useState, useEffect, useRef } from 'react'
import Head from 'next/head'
import { CSSTransition } from 'react-transition-group'
import Title from '../components/title/Title'
import Apples from '../componenßts/title/Apples'
import slideTransition from '../styles/transitions/titleSlide.module.css'
import fadeTransition from '../styles/transitions/titleFade.module.css'
import styles from '../styles/Home.module.css'

export default function Welcome() {
  const titleRef = useRef(null)
  const applesRef = useRef(null)

  const [isShow, setIsShow] = useState(false)
  useEffect(() => setIsShow(true), [])

  return (
    <div className={styles.container}>
      <Head>
        <title>25 Apples</title>
        <link rel="icon" href="/apple_icon.png" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
      </Head>
      <main className={styles.main} style={{ justifyContent: 'center' }}>
        <CSSTransition
          nodeRef={titleRef}
          appear={true}
          in={isShow === true}
          classNames={fadeTransition}
          timeout={1000}
          unmountOnExit
        >
          <Title ref={titleRef} show={setIsShow} />
        </CSSTransition>
        <CSSTransition
          nodeRef={applesRef}
          appear={true}
          in={isShow === true}
          classNames={slideTransition}
          timeout={1000}
          unmountOnExit
        >
          <Apples ref={applesRef} />
        </CSSTransition>
      </main>
    </div>
  )
}
