import Head from "next/head";
import styles from "../../styles/Home.module.css";
import CustomizedCard from "../../components/score/CustomizedCard";


export default function PerfectPage(props) {

    return (
        <div className={styles.container}>
            
            <Head>
                <title>25 Apples</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
    
            <main className={styles.main}>
                <CustomizedCard photo={props.appleId} />
            </main>

        </div>
    );
};



export async function getStaticPaths () {
    const paths = Array.from({length: 9}, (_, index) => index + 1);
    delete paths[4];
    return {
        fallback: 'blocking',  
        paths: paths.map(element => ({
            params: {
                appleId: element.toString(),
            }
        }))
    }
};


export async function getStaticProps (context) {

    const appleId = context.params.appleId; 

    return {
        props: {
            appleId: appleId
        }
    };
};

