import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import CustomizedCard from '../../components/score/CustomizedCard'

export default function PerfectPage({ appleId }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>25 Apples</title>
        <link rel="icon" href="/apple_icon.png" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
      </Head>

      <main className={styles.main}>
        <CustomizedCard photo={appleId} />
      </main>
    </div>
  )
}

export async function getStaticPaths() {
  const paths = Array.from({ length: 9 }, (_, index) => index + 1)
  delete paths[4]
  return {
    fallback: 'blocking',
    paths: paths.map((element) => ({
      params: {
        appleId: element.toString(),
      },
    })),
  }
}

export async function getStaticProps(context) {
  const appleId = context.params.appleId

  return { props: { appleId: appleId } }
}
